#!/bin/sh

set -e

[ -z "$CONFIG" ] && CONFIG=./config
. "$CONFIG"
export H="$PWD"

mkdir -p "$R"/bin "$R"/tmp
cp -f ../bootsh/bootsh "$R"/bin/sh
cp -f ../bootsh/boot.sh "$R"/bin/boot.sh
cp -f ../bootsh/wak.c "$R"/bin/awk
cp -f ../bootsh/Makefile.packages "$R"/tmp/Makefile

mkdir -p "$R"/dev "$R"/proc "$R"/sys

printf '#!/bin/sh\nexec env "$@"' > "$R"/bin/env
chmod +x "$R"/bin/env

mkdir -p "$R"/src
utils/update-chroot.sh
