#!/bin/sh

[ ! -d /etc/dropbear ] && mkdir -p /etc/dropbear
make_key_if_needed() {
	local key=$1
	local bits=$2
	local filename=/etc/dropbear/dropbear_${key}_host_key
	if [ ! -f "$filename" ] ; then
		dropbearkey -s $bits -t $key -f "$filename" | tail -n2 > ${filename}.pub
	fi
}
make_key_if_needed rsa 2048
make_key_if_needed dss 1024
make_key_if_needed ecdsa 384
make_key_if_needed ed25519 256
[ "$1" = "--prereqs" ] && exit 0

exec /bin/dropbear -F 2>&1
