#!/bin/sh

[ -f /etc/ssh/ssh_host_rsa_key ]   || ssh-keygen -t rsa   -N "" -b 2048 -f /etc/ssh/ssh_host_rsa_key
[ -f /etc/ssh/ssh_host_ed25519_key ] || ssh-keygen -t ed25519 -N "" -f /etc/ssh/ssh_host_ed25519_key
[ "$1" = "--prereqs" ] && exit 0

exec /bin/sshd -De 2>&1
